Make bootstrapper available as a CLI and update packit to v2
paketo-community/bootstrapper pull request #206
Opened 2022-03-25 16:23 UTC by sophiewigmore

Resolves #49 and #200 
Make bootstrapper available as a CLI and update packit to v2
- use cobra to make bootstrapper into a CLI tool
- added version command, and a release workflow to publish versioned releases
- updated README.md to reflect how to use the

2022-03-25 16:28 UTC, sophiewigmore commented
The failing integration tests are OK, because they have been removed in this PR. I've removed that as a required check in the repo settings.

2022-03-29 15:15 UTC, ryanmoran requested changes

2022-03-29 15:15 UTC, ryanmoran commented on commands/bootstrap.go
> +	}
```suggestion
	var flags flags
	cmd := &cobra.Command{
		Use:   "run",
		Short: "bootstrap a packit-compliant buildpack",
		RunE: func(cmd *cobra.Command, args []string) error {
			return bootstrapRun(flags)
		},
	}
```

2022-03-29 15:15 UTC, ryanmoran commented on scripts/package.sh
> +    GOOS="windows" go build -ldflags "-X github.com/paketo-community/bootstrapper/commands.bootstrapperVersion=${version}" -o "${ARTIFACTS_DIR}/bootstrapper-windows.exe" main.go
```suggestion
    local ldflags
    ldflags="-X github.com/paketo-community/bootstrapper/commands.bootstrapperVersion=${version}"
    for os in darwin linux; do
      util::print::info "Building bootstrapper on ${os}"
      GOOS="${os}" GOARCH="amd64" go build -ldflags "${ldflags}" -o "${ARTIFACTS_DIR}/bootstrapper-${os}"  main.go
      chmod +x "${ARTIFACTS_DIR}/bootstrapper-${os}"
    done
    util::print::info "Building bootstrapper on windows"
    GOOS="windows" go build -ldflags "${ldflags}" -o "${ARTIFACTS_DIR}/bootstrapper-windows.exe" main.go
```

2022-03-31 15:22 UTC, ryanmoran approved these changes

2022-03-31 15:23 UTC, merged